Changes in dev
SoftRyzen-internship/career-consultant pull request #6
Opened 2024-03-18 15:57 UTC by DmytroSadovskyi

2024-03-18 17:04 UTC, nadiakhoptiuk requested changes

2024-03-19 15:19 UTC, nadiakhoptiuk approved these changes

2024-03-19 15:19 UTC, nadiakhoptiuk commented on components/HeroPlate/HeroPlate.tsx
> +      className={`w-[162px] h-[124px] border-0 rounded-lg shadow-custom bg-white py-[12px] px-[16px] sm:w-[222px] sm:h-[106px] md:p-[20px] md:w-[160px] md:h-[141px] xl:py-[24px] xl:px-[32px]  ${class
тут не підходить фіксована висота і ширина для мобільного, там десь рядки переносяться, десь ні, висота має бути авто
ширину можна через calc рахувати
потрібно прибрати sm, а верстати респонсивно. на sm все одно контейнер фіксується

2024-03-19 15:19 UTC, nadiakhoptiuk commented on components/HeroPlate/HeroPlate.tsx
> +      <p className="text-text01 font-fixel-regular text-[32px] leading-[1.21] mb-2 xl:text-[48px] font-normal xl:mb-3 ">
це спан, а не абзац - за семантикою

2024-03-19 15:19 UTC, nadiakhoptiuk commented on components/HeroPlates/HeroPlates.tsx
> +export default HeroPlates;
у нас іменовані експорти

2024-03-19 15:19 UTC, nadiakhoptiuk commented on components/Input/Input.tsx
> +import Image from 'next/image';
некст іде після реакту

2024-03-19 15:19 UTC, nadiakhoptiuk commented on components/SectionTitle/SectionTitle.tsx
> +export const SectionTitle = ({ text, className = '' }: ISectionTitle) => {
як варіант можна сюди додати пропс center (для центрованих заголовків)

2024-03-19 15:19 UTC, nadiakhoptiuk commented on components/SectionTitle/types.ts
порожній файл?

2024-03-19 15:19 UTC, nadiakhoptiuk commented on tailwind.config.ts
> +        text01: '#001D44',
на майбутнє - рекомендую робити більш зрозумілі позначення для змінних, щоб і на перший погляд було зрозуміло. цифри тут не дуже підходять

2024-03-19 15:19 UTC, nadiakhoptiuk commented on components/Input/Input.tsx
> +  if (errors[name]) {
це можна переписати через const inputStyles = і метод із бібліотеки classnames (приклад - у компоненті Button)

2024-03-19 15:19 UTC, nadiakhoptiuk commented on components/Form/Form.tsx
> +        <Input name="name" label="Ім'я*" type="text" />
потрібно винести ці всі змінні в json для форми. можеш створити в папці data файл form.json і винести туди.

і далі, як мінімум 2 інпути, а то і всі 3 можна буде мепнути. + зручно змінювати контент через одне джерело в папці data. туди ж можна буде винести тексти помилок за потреби

2024-03-19 15:19 UTC, nadiakhoptiuk commented on components/Form/Form.tsx
> +const schema = yup.object().shape({
схему потрібно винести окремо, в utils наприклад

2024-03-19 15:19 UTC, nadiakhoptiuk commented on components/Form/Form.tsx
> +import { Input } from '../Input/Input';
компонент - після зовнішніх бібліотек і типів

2024-03-19 15:52 UTC, nadiakhoptiuk commented on components/HeroPlate/HeroPlate.tsx
> +      <p className="text-text01 font-fixel-regular text-[32px] leading-[1.21] mb-2 xl:text-[48px] font-normal xl:mb-3 ">
font-fixel-regular - такої змінної в Tailwind config немає, стилі не приміняються

line-height не за макетом, на десктопі в картці не вміщається контент разом із падінгами

2024-03-19 15:52 UTC, nadiakhoptiuk commented on components/HeroPlate/HeroPlate.tsx
> +      <p className=" text-text02 text-xs xl:text-[16px] xl: font-medium leading-[1.4] ">
цей текст стандартного шрифту, бо з боді прибрали mulish

2024-03-19 15:52 UTC, nadiakhoptiuk commented on components/HeroPlate/HeroPlate.tsx
> +      className={`w-[162px] h-[124px] border-0 rounded-lg shadow-custom bg-white py-[12px] px-[16px] sm:w-[222px] sm:h-[106px] md:p-[20px] md:w-[160px] md:h-[141px] xl:py-[24px] xl:px-[32px]  ${class
чомусь за макетом немає переносу, може перевірити властивості
![image](https://github.com/SoftRyzen-internship/career-consultant/assets/98387901/c090e467-d329-4ae0-9c78-b9afca9d6655)

2024-03-19 15:52 UTC, nadiakhoptiuk commented on components/Input/Input.tsx
> +      'w-full bg-inputDefaultBg rounded-lg py-6 px-5 xl:p-6 text-sm xl:text-base text-text01 focus:caret-accent focus:bg-inputBg focus:border-inputBorder focus:outline-none focus:border-inputBorderW'
при фокусі додається бордер, і контент скаче. краще просто змінювати колір, за дефолтом бордер робити прозорим. а ще якщо перехід повішати, буде красота)

2024-03-19 15:52 UTC, nadiakhoptiuk commented on components/Form/Form.tsx
> +  email: yup.string().required("E-mail обов'язкове"),
граматична помилка

2024-03-19 15:52 UTC, nadiakhoptiuk commented on components/Input/Input.tsx
> +      {errors[name] && (
під повідомлення про помилку повинно бути зарезервоване місце. не повинен скакати контент якщо з'являється повідомлення під полем

іконка розміщена не по центру: 
![image](https://github.com/SoftRyzen-internship/career-consultant/assets/98387901/739988db-172d-4eab-bc15-d1bde06ac2ea)

2024-03-19 15:55 UTC, merged

2024-03-20 13:35 UTC, chemvic commented on public/meta/ogp/og-image@2x.jpg
видалив

2024-03-20 13:39 UTC, chemvic commented on public/images/hero/hero-photo-mobile.jpg
видалив вузькі

2024-03-20 13:40 UTC, chemvic commented on public/images/choose/illustration-wide-mobile.jpg
видалив wide

2024-03-20 13:42 UTC, chemvic commented on public/images/choose/illustration-tablet.jpg
видалив

2024-03-20 13:42 UTC, chemvic commented on public/icons/quote-solid.svg
видалив

2024-03-20 13:43 UTC, chemvic commented on public/icons/left-arrow.svg
видалив

2024-03-20 13:50 UTC, chemvic commented on public/icons/favicon-svg.svg
зробив та поклав  до app/