Feature/socials
SoftRyzen-internship/career-consultant pull request #9
Opened 2024-03-19 11:30 UTC by AnastasiiaYurchenko

Добавила компонент Соц. мереж та виправила в компоненті Лого послідовність підключення імпортів

2024-03-19 16:47 UTC, DmytroSadovskyi approved these changes

2024-03-19 16:48 UTC, DmytroSadovskyi requested changes
Потрібно вирішити конфлікти

2024-03-19 17:22 UTC, AnastasiiaYurchenko commented
вирішила конфлікти

2024-03-20 09:30 UTC, DmytroSadovskyi approved these changes

2024-03-20 09:30 UTC, merged